Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -26,8 +26,9 @@ jobs:
       - name: Install dependencies
         run: npm install
 
-      - name: Build project
-        run: CI=false yarn build
+      - name: Force Build (Ignore Errors)
+        run: |
+          CI=false yarn build || echo "Build failed, continuing with deployment"
 
       - name: Deploy to GitHub Pages
         uses: JamesIves/github-pages-deploy-action@v4
